apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-deployment
  labels:
    app: boot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: boot
  template:
    metadata:
      labels:
        app: boot
    spec:
      containers:
      - name: boot
        image: vishalswamiust/dockerhub:bootdocker
        ports:
        - containerPort: 8090